[build]
command = "npm run build"
publish = "dist"

[context.production.environment]
  HUGO_VERSION = "0.88.1"

[build.redirects]
  "/" = "/index.html 200!"
  "/about" = "/about.html 200"
  "/contact" = "/contact.html 200"